name: FirstPipelineForGeoServerDatadir

jobs:
- deployment: geoserverdatadir
  environment: dev
  pool:
    name: Staging
  strategy:                 
    runOnce:
      deploy: 
        steps:       
        - script: |
           hostname
           cd /mnt/data_dir
           git fetch --all
           git checkout datadir
           echo "committing local changes to the datadir"
           git add .
           git commit -m "`date` datadir test"

           echo "pushing to Azure devops"
           git push -u dorset datadir
          displayName: GeoServer Datadir Save Latest Changes
